# docker-compose.prod.yml (Extended config for PRODUCTION env.)
# run with
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3.9'

services:
  web:
  build:
    context: ./
    dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
