# docker-compose run --rm backend sh -c "python manage.py createsuperuser"
version: '3.9'

services: 
  backend:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ./data/web:/vol/web
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    env_file:
      - ./.env.dev