# docker-compose -f docker-compose-deploy.yml run --rm backend sh -c "python manage.py createsuperuser"
# docker-compose -f docker-compose-deploy.yml exec db psql --username=prod_user --dbname=prod_db
# docker-compose -f docker-compose-deploy.yml down -v 
version: '3.9'

services: 
  backend:
    build: 
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    restart: always
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    build: 
      context: ./proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
