version: '3.9'

services: 
  backend:
    build: 
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    restart: always
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

  proxy:
    build: 
      context: ./proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: