# docker-compose.override.yml (Extended config for DEVELOPMENT env.)
# run with
# docker-compose up -d
version: '3.9'

services:
  web:
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
